-- Local development seed (runs only on `supabase db reset`; `db push` does
-- not run seed files, so production still gets the invite key from Vault).
--
-- The invite functions encrypt links under a Vault secret named `invite`.
-- Generate a fresh random key per reset so invites work out of the box,
-- without committing any secret.
select vault.create_secret(
  encode(extensions.gen_random_bytes(32), 'hex'),
  'invite',
  'local dev invite key (generated by seed.sql)'
)
where not exists (select 1 from vault.secrets where name = 'invite');
